spring.application.name=backend
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

football.api.url=https://api.football-data.org/v4
football.api.token=a9737221ef984f7596252f2726cbda58